services:
  - type: web
    name: freshkeep-app
    env: node
    plan: free
    buildCommand: npm install && npm run build && npx puppeteer browsers install chrome
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
